# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vaani.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vaani.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bvaani.proto\x12\x05vaani\"\x1e\n\nAudioChunk\x12\x10\n\x08pcm_data\x18\x01 \x01(\x0c\"\x1d\n\tVadSignal\x12\x10\n\x08speaking\x18\x01 \x01(\x08\"%\n\x0fSessionMetadata\x12\x12\n\nsession_id\x18\x01 \x01(\t\"\t\n\x07\x45ndCall\"c\n\x11\x43\x61llClientMessage\x12\"\n\x05\x61udio\x18\x01 \x01(\x0b\x32\x11.vaani.AudioChunkH\x00\x12\x1f\n\x03vad\x18\x02 \x01(\x0b\x32\x10.vaani.VadSignalH\x00\x42\t\n\x07payload\"\x92\x01\n\x11\x43\x61llServerMessage\x12*\n\x08metadata\x18\x01 \x01(\x0b\x32\x16.vaani.SessionMetadataH\x00\x12\"\n\x05\x61udio\x18\x02 \x01(\x0b\x32\x11.vaani.AudioChunkH\x00\x12\"\n\x08\x65nd_call\x18\x03 \x01(\x0b\x32\x0e.vaani.EndCallH\x00\x42\t\n\x07payload\"d\n\x12\x41gentClientMessage\x12\"\n\x05\x61udio\x18\x01 \x01(\x0b\x32\x11.vaani.AudioChunkH\x00\x12\x1f\n\x03vad\x18\x02 \x01(\x0b\x32\x10.vaani.VadSignalH\x00\x42\t\n\x07payload\"C\n\x12\x41gentServerMessage\x12\"\n\x05\x61udio\x18\x01 \x01(\x0b\x32\x11.vaani.AudioChunkH\x00\x42\t\n\x07payload2S\n\x0b\x43\x61llService\x12\x44\n\nStreamCall\x12\x18.vaani.CallClientMessage\x1a\x18.vaani.CallServerMessage(\x01\x30\x01\x32\\\n\x0c\x41gentService\x12L\n\x10StreamAgentAudio\x12\x19.vaani.AgentClientMessage\x1a\x19.vaani.AgentServerMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vaani_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOCHUNK']._serialized_start=22
  _globals['_AUDIOCHUNK']._serialized_end=52
  _globals['_VADSIGNAL']._serialized_start=54
  _globals['_VADSIGNAL']._serialized_end=83
  _globals['_SESSIONMETADATA']._serialized_start=85
  _globals['_SESSIONMETADATA']._serialized_end=122
  _globals['_ENDCALL']._serialized_start=124
  _globals['_ENDCALL']._serialized_end=133
  _globals['_CALLCLIENTMESSAGE']._serialized_start=135
  _globals['_CALLCLIENTMESSAGE']._serialized_end=234
  _globals['_CALLSERVERMESSAGE']._serialized_start=237
  _globals['_CALLSERVERMESSAGE']._serialized_end=383
  _globals['_AGENTCLIENTMESSAGE']._serialized_start=385
  _globals['_AGENTCLIENTMESSAGE']._serialized_end=485
  _globals['_AGENTSERVERMESSAGE']._serialized_start=487
  _globals['_AGENTSERVERMESSAGE']._serialized_end=554
  _globals['_CALLSERVICE']._serialized_start=556
  _globals['_CALLSERVICE']._serialized_end=639
  _globals['_AGENTSERVICE']._serialized_start=641
  _globals['_AGENTSERVICE']._serialized_end=733
# @@protoc_insertion_point(module_scope)
