# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import vaani_pb2 as vaani__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vaani_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CallServiceStub(object):
    """── Services ──────────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamCall = channel.stream_stream(
                '/vaani.CallService/StreamCall',
                request_serializer=vaani__pb2.CallClientMessage.SerializeToString,
                response_deserializer=vaani__pb2.CallServerMessage.FromString,
                _registered_method=True)


class CallServiceServicer(object):
    """── Services ──────────────────────────────────────────────────────────────────

    """

    def StreamCall(self, request_iterator, context):
        """Bidirectional: caller sends audio+VAD, receives TTS audio back.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CallServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamCall': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamCall,
                    request_deserializer=vaani__pb2.CallClientMessage.FromString,
                    response_serializer=vaani__pb2.CallServerMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vaani.CallService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vaani.CallService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CallService(object):
    """── Services ──────────────────────────────────────────────────────────────────

    """

    @staticmethod
    def StreamCall(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/vaani.CallService/StreamCall',
            vaani__pb2.CallClientMessage.SerializeToString,
            vaani__pb2.CallServerMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AgentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamAgentAudio = channel.stream_stream(
                '/vaani.AgentService/StreamAgentAudio',
                request_serializer=vaani__pb2.AgentClientMessage.SerializeToString,
                response_deserializer=vaani__pb2.AgentServerMessage.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamAgentAudio(self, request_iterator, context):
        """Bidirectional: human agent sends audio+VAD, receives caller audio.
        Pass session-id and agent-id as gRPC request metadata headers.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamAgentAudio': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamAgentAudio,
                    request_deserializer=vaani__pb2.AgentClientMessage.FromString,
                    response_serializer=vaani__pb2.AgentServerMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vaani.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vaani.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamAgentAudio(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/vaani.AgentService/StreamAgentAudio',
            vaani__pb2.AgentClientMessage.SerializeToString,
            vaani__pb2.AgentServerMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
